### ISSUE TITLE
Add functionality to remove sample and project filters

### ISSUE THREAD

**Issue by ODiogoSilva** [ODiogoSilva/report-nf#13]

**Comment by bfrgoncalves** [comment]
This option is now implemented on [https://github.com/ODiogoSilva/report-nf/commit/1630159e063e4197a93b7daf83da4d4aae4ab734](url)

**Comment by bfrgoncalves** [comment]
This is now implemented on 1630159e063e4197a93b7daf83da4d4aae4ab734

**Comment by bfrgoncalves** [comment]
The bug for removing filters is now fixed by setting the content of the popover dynamically
