### ISSUE TITLE
Add scroll on sidebar menu

### ISSUE THREAD

**Issue by bfrgoncalves** [ODiogoSilva/report-nf#15]
Submit button on filters disappear on lower resolution displays because of the large number of sliders and input buttons. Need to add a scroll to prevent this from happening.

**Comment by bfrgoncalves** [comment]
A fixed height of 500px and a scroll was added to the filters collapse div. 029f4d1ccf72dc1827c5ae02892bc7e57fbe6fb6

**Comment by ODiogoSilva** [comment]
This was a nice catch. I further suggest (and implemented) moving the submit/reset buttons to outside of the scroll div, so that users won't have to scroll down when they want to submit/reset filters

**Comment by bfrgoncalves** [comment]
This is now implemented
