### ISSUE TITLE
Add mock label when there are no active filters 

### ISSUE THREAD

**Issue by ODiogoSilva** [ODiogoSilva/report-nf#17]
Currently, the popover label is awkward when there is no active filters. This could be enhanced by placing a mock label saying "No active filters", which is automatically removed when the first filter is added, and re-inserted when all filters were removed

**Comment by bfrgoncalves** [comment]
This option is now implemented with the label "No filters applied!" 1455cd4d652975d5fd8cfae8a9f65903eb241133
