### ISSUE TITLE
Add metadata table

### ISSUE THREAD

**Issue by bfrgoncalves** [ODiogoSilva/report-nf#22]
A table with metadata associated with each strain would be nice for mapping between results and the metadata.

**Comment by bfrgoncalves** [comment]
Table is now implemented on commit 01961510566717554438650681b647a14dfb85b9
Filters are missing on metadata

**Comment by ODiogoSilva** [comment]
Filter of metadata is now supported via https://github.com/ODiogoSilva/report-nf/commit/c9272a74bcdcbffccb0f9f0b8a1ed8114fcc5170
