### ISSUE TITLE
INNUca not reporting True Coverage Fail

### ISSUE THREAD

**Issue by bfrgoncalves** [ODiogoSilva/report-nf#63]
True coverage is reporting correctly in Pathotyping but not in the INNUca pipeline. If it fails in the Pathotyping, it should also fail in INNUca. One of the cases below.

![image](https://user-images.githubusercontent.com/5382566/35735636-620a8464-081d-11e8-8e86-dacd4cf61ad8.png)

**Comment by ODiogoSilva** [comment]
This was fixed by reporting the mlst to convey a consistent behaviour between pathotyping and innuca.
