### ISSUE TITLE
Add functionality to filter samples and projects from the report

### ISSUE THREAD

**Issue by ODiogoSilva** [ODiogoSilva/report-nf#7]
This would basically mean to have a filter when building the data structures for the tables and plots

**Comment by ODiogoSilva** [comment]
Fields to filter:

- Sample ID: text
- Project ID: text
- QC grade: dropdown?
- Bp: slider
- reads: slider
- coverage: slider
- contigs: slider
- assembled bp: slider

**Comment by bfrgoncalves** [comment]
DOM elements were created but we still need to code the triggers.
